### PR TITLE
update sources fields

### LINKED ISSUE #300: Note.source should be a DatabaseReference
The Note.source property should be a DatabaseReference to a Person object.

### LINKED ISSUE #320: add Utterance.source
**Describe the solution you'd like**

Sometimes DLx Utterance objects will be used outside of a text, as standalone pieces of data. In this case, it's important to capture the source of the information.

The Utterance schema should support a `source` field, which is a simple string (not a MultiLangString).

### LINKED ISSUE #337: update source fields
This is a meta-issue for planning changes to source/bibliography fields, and tracking those issues.

# Places to Address
* `Lexeme` (remove field from Lexeme?)
* `LexemeForm`
* `Note` (#300)
* `Sense` (source/speaker)
* `Utterance` (source/speaker) (#320)

# Additional Changes
- [x] update any relevant example data
  - **NB:** This needs to be done for any schemas that also _contain_ one of the affected schemas in the example data.
- [x] update version numbers of affected schemas
  - **NB:** The type of version bump to make depends on the difference between this PR and the current `master` branch, _not_ the difference between this PR and earlier versions of this PR.

# Original Proposals
- [x] `Note.source` should always be a `Person` object (ie who wrote the Note, even if the object is just their name)
- [x] Remove required properties for `Person` objects (unless there is a functional reason to require family and given names)
- [x] `Utterance.speaker` should be a `Person` object
- [x] update description of `Utterance.speaker` - it no longer needs to be an abbreviation
- [x] Add `Utterance.source` for Utterances taken out of context, like sets of utterances to be used as examples in publications. There's not going to be any sort of database to cross-reference. The user just needs to be able to identify where the data comes from. Strongly recommended when an `Utterance` is not part of a Text - `MultiLangString`
- [x] The sources property in various schemas should be an array of DatabaseReferences to either Person objects or BibliographicReference objects. This affects the following properties:
- [x] Lexeme.sources
- [x] LexemeForm.sources
- [x] Sense.sources
The sources fields should not contain DatabaseReferences to Texts, Utterances, Word Tokens, or Morpheme Tokens.

### PR DESCRIPTION
**Pull request by vadekh**
# Related Issues

This is a fairly large PR which encompasses multiple issues relating to source and bibliography fields.

**Primary Issue:** closes #337

**Subsidiary Issues Also Addressed in this PR**
* `Note` (closes #300)
* `Utterance` (closes #320)

## Changelog

(Some of these changes may be reverted or further updated depending on the discussion in #337.)

- **CHANGE:** Lexeme.sources are DatabaseReferences to Person and/or BibliographicReference objects
- **CHANGE:** Note.source is a DatabaseReference to a Person object
- **CHANGE:** Sense.sources are DatabaseReferences
- **CHANGE:** Utterance.speaker is a Person object

### CODE REVIEW

**Comment by vadekh** [comment]
This also now addresses this issue: https://github.com/digitallinguistics/spec/issues/337

Change Utterance.speaker to be a Person object
Update Utterance.speaker description
Update description of Lexeme.source to reflect new functionality
Require Lexeme.sources.source objects to be DatabaseReference objects
Update LexemeForm.sources description
Require LexemeForm.sources.source to be DatabaseReference object
Update example data for LexemeForm and Lexeme
Fix typo in Lexeme.sources description
Update Sense.source description
Require Sense.sources.source to be DatabaseReference objects
Update example data
version bumps

**Comment by Calvin1119** [comment]
The tests are passing for this. It does seem a little confusing that there are some source(s) fields that allow both Person and BibliographicReference objects and some that only take Person objects. Also, for those types of source fields (as seen in Sense), there doesn't seem to be any actual validation that these objects are actually of the correct types (Person/BibliographicRef instead of any other type of DatabaseRef). This PR should be good to go, but that might be another issue to take a look at in the future.

**Comment by dwhieb** [comment]
@Calvin1119 I think you're right that the changes surrounding the Source fields needs a little rethinking before we merge this. I'll start a discussion on the relevant issue.

**Comment by vadekh** [comment]
I have TEST in the code in 3 files, where there should be a speaker source's abbreviation. I was unsure of what data to test against to maintain the accuracy of the data.
Additionally, I have separated the Person sources and the BibliographicReference sources for Lexeme, LexemeForm, and Sense. I designated a referenceType in all of the concerned fields, but I still do not really understand if/how the validation happens in the DatabaseReference schema.
@dwhieb

**Comment by dwhieb** [comment]
This is great work - thanks @vadekh! I'm going to steal this PR and make some additional changes based on our convo in #337.

**Pull request merged**
